app/Http/routes.php
<?php

Route::get('/', function () {
    return view('content_holder', [
        'content' => file_get_contents(public_path('static/index.html'))
    ]);
});

Route::auth();

Route::get('/questions', function () {
    return view('questions', [
        'imagesMapping' => file_get_contents(public_path('mix-manifest.json'))
    ]);
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('/admin', ['as' => 'results.index', 'uses' => 'ResultController@index']);
    Route::get('/admin/questions/{result}', ['as' => 'questions.show', 'uses' => 'ResultController@show']);
    Route::post('/admin/results/export', ['as' => 'results.export', 'uses' => 'ResultController@export']);
});

app/Result.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
    protected $fillable = ['age', 'skin_type', 'skin_tan', 'pores_visibility', 'black_spots', 'wrinkles', 'skin_tightness', 'stains', 'akne', 'makeup', 'cleanup', 'purpose', 'subscribtion', 'name', 'email', 'venue_name',];

    protected $ages = [
        '0'=>'18-25',
        '1'=>'26-30',
        '2'=>'31-35',
        '3'=>'36-45',
        '4'=>'46-55',
        '5'=>'55+',
    ];
    protected $skinTypes = [
        '0'=>'ЧУВСТВИТЕЛНА',
        '1'=>'СУХА',
        '2'=>'НОРМАЛНА',
        '3'=>'СМЕСЕНА',
        '4'=>'МАЗНА',
    ];
    protected $skinTans = [
        '0'=>'НЕ',
        '1'=>'МАЛКО',
        '2'=>'МНОГО',
    ];
    protected $poresVisibilities = [
        '0'=>'НЕЗАБЕЛЕЖИМИ',
        '1'=>'ВИДИМИ',
    ];
    protected $blackSpots = [
        0=>'НЕ',
        1=>'ДА',
    ];
    protected $wrinkleses = [
        '0'=>'НЯМА',
        '1'=>'ФИНИ, МИМИЧЕСКИ',
        '2'=>'ВИДИМИ',
        '3'=>'ДЪЛБОКИ',
    ];
    protected $skinTightnesses = [
        '0'=>'ПЛЪТНА И ЕЛАСТИЧНА',
        '1'=>'НАМАЛЕНА',
        '2'=>'ВИДИМО ОТПУСНАТА',
        '3'=>'ДЪЛБОКИ',
    ];
    protected $stainses = [
        '0'=>'НЕ',
        '1'=>'НА МЕСТА',
        '2'=>'ДА',
    ];
    protected $aknes = [
        '0'=>'НЕ',
        '1'=>'ДА',
    ];
    protected $makeups = [
        '0'=>'НЕ ИЗПОЛЗВАМ',
        '1'=>'Само околоочен',
        '2'=>'Лек грим',
        '3'=>'Дълготраен',
    ];
    protected $cleanups = [
        '0'=>'С памучни тампони',
        '1'=>'С Измиващи продукти',
        '2'=>'С ПОЧИСТВАЩИ КЪРПИЧКИ',
        '3'=>'НЕ СИ ПОЧИСТВАМ ГРИМА ЕЖЕДНЕВНО',
    ];
    protected $bools = [
        0=>'НЕ',
        1=>'ДА',
    ];

    protected $tips = [
        '0'=>[
            'title'=>'Съвети за чувствителна кожа',
            'tips'=>[
                'Нежно потупвайте лицето си с кърпа, след като го почистите, вместо да го търкате.',
                'Обръщайте внимание на храненето си – пикантните подправки не са полезни за кожата ви.',
                'Изберете крем, който осигурява защита от вредните влияния на околната среда.'
            ]
        ],
        '1'=>[
            'title'=>'Съвети за суха кожа',
            'tips'=>[
                'Можете да помогнете на кожата си, като се храните здравословно. Пийте по 2 литра вода всеки ден.',
                'Дневните кремове със слънцезащитен фактор защитават кожата ви от UV лъчението.',
                'Продуктите за грижа с естествени масла облекчават кожата.'
            ]
        ],
        '2'=>[
            'title'=>'Съвети за нормална кожа',
            'tips'=>[
                'Редовната дневна и нощна грижа поддържа кожата ви свежа.',
                'Нежното ексфолиране премахва нечистотите и мъртвите кожни клетки.',
                'Като нанасяте крема си за лице с нежни масажни движения, стимулирате кръвообращението.'
            ]
        ],
        '3'=>[
            'title'=>'Съвети за смесена кожа',
            'tips'=>[
                'Почиствайте внимателно кожата си преди нанасянето на продукти за грижа за кожата на лицето.',
                'Използвайте хладка вода вместо гореща или леденостудена.',
                'Редовно използвайте хидратиращ продукт – количество с размер на лешник е достатъчно!'
            ]
        ],
        '4'=>[
            'title'=>'Съвети за мазна кожа',
            'tips'=>[
                'Изключително важно е да премахвате грима си вечер, защото през нощта той може да запуши порите ви.',
                'Третирайте кожата си с нежен скраб и маска за лице веднъж седмично.',
                'Долу ръцете: не стискайте черните точки или пъпките!'
            ]
        ],
    ];

    public function products()
    {
        return $this->hasMany('App\Product');
    }

    public function getAgeAttribute($value)
    {
        return $this->ages[(int) $value];
    }

    public function getSkinTypeAttribute($value)
    {
        return $this->skinTypes[(int) $value];
    }
    public function getSkinTanAttribute($value)
    {
        return $this->skinTans[(int)$value];
    }
    public function getPoresVisibilityAttribute($value)
    {
        return $this->poresVisibilities[(int)$value];
    }
    public function getBlackSpotsAttribute($value)
    {
        return $this->blackSpots[(int)$value];
    }
    public function getWrinklesAttribute($value)
    {
        return $this->wrinkleses[(int)$value];
    }

    public function getSkinTightnessAttribute($value)
    {
        return $this->skinTightnesses[(int)$value];
    }
    public function getStainsAttribute($value)
    {
        return $this->stainses[(int)$value];
    }
    public function getAkneAttribute($value)
    {
        return $this->aknes[(int)$value];
    }
    public function getMakeupAttribute($value)
    {
        return $this->makeups[(int)$value];
    }
    public function getCleanupAttribute($value)
    {
        $result = '';
        foreach (json_decode($value) as $cleanup){
            $result.=$this->cleanups[$cleanup].' ';
        }
        return rtrim($result," ");
    }
    public function getPurposeAttribute($value)
    {
        return $this->bools[(int)$value];
    }
    public function getSubscribtionAttribute($value)
    {
        return $this->bools[(int)$value];
    }
    public function getTipAttribute()
    {
        return $this->tips[$this->attributes['skin_type']];
    }

    public function getCreatedAtAttribute()
    {
        return date('F d, Y H:m', strtotime($this->attributes['created_at']));
    }
}

resources/views/content_holder.blade.php
{!! $content !!}

resources/views/export.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Поръчки</title>
    <font face="arial">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <style type="text/css">
            td {
                padding-right: 10px;
            }
        </style>
        </head>
<body>
<table class="display" width="100%" cellspacing="0">
    <tr>
        <td>Обект</td>
        <td>Възраст</td>
        <td>Тип Кожа</td>
        <td>Тенът ми е неравномерен</td>
        <td>Видимост</td>
        <td>Имам черни точки</td>
        <td>Наличие на бръчки</td>
        <td>Еластичност на кожата</td>
        <td>Петна</td>
        <td>Страдам от акне</td>
        <td>Използвам грим</td>
        <td>Почиствам грима си</td>
        <td>Цели на приложението</td>
        <td>Абонамент</td>
        <td>Име</td>
        <td>email</td>
        <td>Година</td>
        <td>Дата</td>
        <td>Време</td>
        <td>Продукти</td>
    </tr>
    @foreach ($results as $result)
        <tr>
            <td>{{$result->venue_name or 'No venue'}}</td>
            <td>{{$result->age}}</td>
            <td>{{$result->skin_type}}</td>
            <td>{{$result->skin_tan}}</td>
            <td>{{$result->pores_visibility}}</td>
            <td>{{$result->black_spots}}</td>
            <td>{{$result->wrinkles}}</td>
            <td>{{$result->skin_tightness}}</td>
            <td>{{$result->stains}}</td>
            <td>{{$result->akne}}</td>
            <td>{{$result->makeup}}</td>
            <td>{{$result->cleanup}}</td>
            <td>{{$result->purpose}}</td>
            <td>{{$result->subscribtion}}</td>
            <td>{{$result->name or 'Anonymous Name'}}</td>
            <td>{{$result->email or 'Anonymous Email'}}</td>
            <td>{{(new \Carbon\Carbon($result->created_at))->format('Y')}}</td>
            <td>{{(new \Carbon\Carbon($result->created_at))->format('F d')}}</td>
            <td>{{(new \Carbon\Carbon($result->created_at))->format('H:m')}}</td>
            <td>
                @foreach ($result->products as $product)
                    {{$product->title}}
                    <br>
                    @if($product->subitem_title)
                        {{$product->subitem_title}}
                        <br>
                    @endif
                @endforeach
            </td>
        </tr>
    @endforeach
</table>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default login-container">
                    <div class="panel-heading"><img src="{{asset('img/logo_nivea.jpg')}}" alt=""></div>
                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ url('login') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

                                    @if ($errors->has('email'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                <label for="password" class="col-md-4 control-label">Password</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control" name="password" required>

                                    @if ($errors->has('password'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> Remember Me
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Login
                                    </button>

                                    <a class="btn btn-link" href="{{ url('password.request') }}">
                                        Forgot Your Password?
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-7">
                        <h3 class="panel-title">Results</h3>
                    </div>
                    <div class="col-sm-4">
                        <form action="{{route('results.export')}}" method="post">
                        <h1 class="panel-title">Limit results to:</h1>
                        <input type="date" name="date_to">
                        <input type="submit" value="Export">
                            {{ csrf_field() }}
                    </form>
                    </div>
                    <div class="col-sm-1">
                        {{--<a class="btn btn-default" href="{{route('results.export')}}"> Export</a>--}}
                        @include('partials.logout')
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <table class="table table-responsive">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Venue</th>
                        <th scope="col">Name</th>
                        <th scope="col">Е-mail</th>
                        <th scope="col">Questions</th>
                        <th scope="col">Recommended Products</th>
                        <th scope="col">Year</th>
                        <th scope="col">Date</th>
                        <th scope="col">Time</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($results as $index => $result)
                        <tr>
                            <td>{{$result->id}}</td>
                            <td>{{$result->venue_name or 'No venue'}}</td>
                            <td>{{$result->name or "Anonymous Name"}}</td>
                            <td>{{$result->email or "Anonymous Email" }}</td>
                            <td><a href="{{route('questions.show',$result)}}">Details</a></td>
                            <td>
                                <ul>
                                    @foreach ($result->products as $product)
                                        <li>{{$product->title}}</li>
                                        @if($product->subitem_title)
                                            <li>{{$product->subitem_title}}</li>
                                        @endif
                                    @endforeach
                                </ul>
                            </td>
                            <td>{{(new \Carbon\Carbon($result->created_at))->format('Y')}}</td>
                            <td>{{(new \Carbon\Carbon($result->created_at))->format('F d')}}</td>
                            <td>{{(new \Carbon\Carbon($result->created_at))->format('H:m')}}</td>
                        </tr>
                    @endforeach
                    </tbody>

                </table>
                <div align="center">{{ $results->links()}}</div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/questions.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <ebeauty :manifest="{{$imagesMapping}}"></ebeauty>
</div>
@endsection

resources/views/show.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container results">
        <div class="row">
            <div class="panel panel-info">
                <div class="panel-heading">

                    <div class="row">
                        <div class="col-sm-9">
                            <h3 class="panel-title">{{$result->name or 'Anonymous Name'}} - {{$result->email  or 'Anonymous Email'}}</h3>
                        </div>
                        <div class="col-sm-3">
                            <a href="{{ url()->previous() }}" class="btn btn-default">Back</a>
                            @include('partials.logout')
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class=" col-md-5 col-lg-5 ">
                            <table class="table">
                                <tbody>

                                <tr>
                                    <td>Възраст</td>
                                    <td>{{$result->age}}</td>
                                </tr>
                                <tr>
                                    <td>Тип Кожа</td>
                                    <td>{{$result->skin_type}}</td>
                                </tr>
                                <tr>
                                    <td>Тенът ми е неравномерен</td>
                                    <td>{{$result->skin_tan}}</td>
                                </tr>
                                <tr>
                                    <td>Видимост</td>
                                    <td>{{$result->pores_visibility}}</td>
                                </tr>
                                <tr>
                                    <td>Имам черни точки</td>
                                    <td>{{$result->black_spots}}</td>
                                </tr>
                                <tr>
                                    <td>Наличие на бръчки</td>
                                    <td>{{$result->wrinkles}}</td>
                                </tr>
                                <tr>
                                    <td>Еластичност на кожата</td>
                                    <td>{{$result->skin_tightness}}</td>
                                </tr>
                                <tr>
                                    <td>Петна</td>
                                    <td>{{$result->stains}}</td>
                                </tr>
                                <tr>
                                    <td>Страдам от акне</td>
                                    <td>{{$result->akne}}</td>
                                </tr>
                                <tr>
                                    <td>Използвам грим</td>
                                    <td>{{$result->makeup}}</td>
                                </tr>
                                <tr>
                                    <td>Почиствам грима си</td>
                                    <td>{{$result->cleanup}}</td>
                                </tr>
                                <tr>
                                    <td>Purpose</td>
                                    <td>{{$result->purpose}}</td>
                                </tr>
                                <tr>
                                    <td>Subscribtion</td>
                                    <td>{{$result->subscribtion}}</td>
                                </tr>

                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-7 col-lg-7 recommended-products" align="center">
                            <h4>Recommended Products</h4>
                            <ul class="list-group list-group-flush">
                                @foreach ($result->products as $index=> $product)
                                    <li class="list-group-item">{{$product->title}}</li>
                                    @if($product->subitem_title)
                                        <li class="list-group-item">{{$product->subitem_title}}</li>
                                    @endif
                                @endforeach
                            </ul>

                            @foreach ($result->products as $index=> $product)
                                <img src="{{$product->imagePath()}}">
                                @if($product->subitem)
                                    <img src="{{$product->imagePathSubitem()}}">
                                @endif
                            @endforeach
                            <h4>{{$result->tip['title']}}</h4>

                            <ul class="list-group list-group-flush">
                                @foreach ($result->tip['tips'] as $tip )
                                    <li class="list-group-item">{{$tip}}</li>
                                @endforeach
                            </ul>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection